### ISSUE TITLE
Version 0.9.3 not working in Vaadin 7.7.0

### ISSUE THREAD

**Issue by slibert** [tltv/gantt#45]
Since migrating to Vaadin 7.7.0, addon is not working anymore. It complains about missing libraries :

java.lang.NoClassDefFoundError: com/google/gwt/i18n/client/constants/TimeZoneConstants
java.lang.NoClassDefFoundError: com/google/gwt/i18n/shared/Localizable

Regards

**Comment by slibert** [comment]
Just found what was going wrong.
As stated in 7.7.0 release note, gwt classes has been extracted to another package. This pack was not included by default in my War.

See https://vaadin.com/download/release/7.7/7.7.0/release-notes.html#gwtdep

So a simple ivy import did the trick : 
`		<dependency org="com.vaadin.external.gwt" name="gwt-servlet" rev="2.7.0.vaadin3" />`

Could have been maven also ;-)

Thanks for the great addon !
